"""The published page — and the two rules the index checker structurally cannot carry.

`ADR-0004` (in the private index) puts one checker over all twelve published surfaces and
assertions in the repositories that have a page test. This repository had none, and S4 needs
one for a reason that is not convenience: **the checker reads a page's HTML and its CSS, and
cannot see this repository's artifacts.** So the two rules S4 is actually about are invisible
to it —

* *every figure the page prints is a figure a committed artifact prints* — it has nothing to
  compare against;
* *clause 2 binds where an artifact can source the tile* — its `clause_2_tiles` returns
  `n/a, §5.1 fallback applies` for any page with no tiles, before and after, because it
  cannot tell "exempt" from "nobody built tiles".

Everything else on this page — the ten tokens, the dark override, the wrapper, the eyebrow,
the card metadata, the system font stack, the separator — the checker does carry, and is not
restated here. Duplicating it in twelve places is the option `ADR-0004` rejected.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = (ROOT / "docs" / "index.html").read_text(encoding="utf-8")

#: What this page is allowed to quote: the evaluation report, generated by
#: `src/pl_jobs_lora/eval/report.py` and covered by `tests/test_eval_report.py`. `.gitignore`
#: keeps `results/eval/predictions/` out and says in the same breath that *"only the
#: numbers-only report.{json,md} is versioned"* — so this is the whole of what a reader of
#: this repository can check a page figure against.
ARTIFACTS = (
    Path("results/eval/report.md"),
    Path("results/eval/report.json"),
    # Two ADRs, named as sources rather than left as an exception. `results/probe/` is
    # gitignored, so the base-model probe's figures exist only in the ADR that recorded them,
    # and the corpus counts likewise. `ADR-0012` admits a committed non-generated source when
    # the page's artifact set names it - and naming it is what makes the alternative visible:
    # version `results/probe/` and the first of these two comes off this list.
    Path("docs/decisions/0001-base-model-selection.md"),
    Path("docs/decisions/0002-dataset-and-labeling.md"),
)

#: `0007` §5.0: a quotation is a digit sequence. The group separator is the page's typography —
#: clause 8 makes the page write `U+202F` where the artifact writes a comma — so both sides are
#: reduced to digits before comparing, and neither side's separator is part of the claim.
#: The separators a page may write where an artifact writes a comma.
_SEP_CHARS = "\u202f\u00a0\u2009 "
_SEPARATORS = str.maketrans(dict.fromkeys("," + _SEP_CHARS, ""))

#: Numbers a reader sees that are not results, cut out of the rendered text before tokenising
#: rather than excused afterwards. Each is a *shape* with a reason, never a value: a list of
#: allowed values goes stale in silence, which is what `0007` §5.0 sentence 2 is about.
_NOT_A_RESULT = (
    (r"\b(?:19|20)\d{2}-\d{2}-\d{2}\b", "a date is a fact about a run, not a cell of one"),
    (r"\b(?:19|20)\d{2}\b", "years"),
    (r"\b[AP]\d\b", "the portfolio's own ranking codes"),
    # A model's name is an identifier. `Qwen2.5-1.5B` reads as the figures 2.5 and 1.5,
    # and `claude-haiku-4-5` as 4 and 5 - none of them a measurement of anything.
    (r"\b(?:Qwen|Bielik|Llama|Mistral)[\w.-]*", "a model name carries version digits"),
    (r"\bclaude-[\w-]+", "the API model's name"),
    # A figure the page has withdrawn, marked `<s class="withdrawn">` so a reader sees
    # it is not a claim. No artifact prints a number that was wrong, and forbidding it
    # would forbid the correction - which is the one section on this page whose whole
    # subject is a figure that should not have been published.
    (r'<s class="withdrawn">.*?</s>', "a figure the page has struck"),
)


def _artifact_text() -> str:
    return "\n".join((ROOT / name).read_text(encoding="utf-8") for name in ARTIFACTS)


def _rendered_text() -> str:
    """What a reader sees: no stylesheet, no comments, no attributes, no tags.

    Comparing the **raw HTML** was the first attempt and it is hopeless — a URL's `223`, a
    hex literal's digits and an entity's `160` all read as claims, and the exemption list
    needed to silence them would be wider than the rule. `apply-scout`'s equivalent test
    reads rendered text for the same reason, and it is the reason.
    """
    text = re.sub(r"<(style|script)\b.*?</\1>", " ", PAGE, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    # Twice on purpose: a shape written in markup — the struck span — has to go before the
    # tags do, and a shape written in prose only exists after they are gone.
    for pattern, _why in _NOT_A_RESULT:
        text = re.sub(pattern, " ", text, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"&#\d+;|&\w+;", " ", text)
    for pattern, _why in _NOT_A_RESULT:
        text = re.sub(pattern, " ", text)
    return text


#: A whole figure. **The plain space is not in the class**, though it is in
#: `_SEP_CHARS`: clause 8 makes a grouped figure use `U+202F`, and admitting the
#: ordinary space here welds two adjacent table cells into one token — `0.05 0.04`
#: reads as `0.050.04` and matches nothing. That is the welding `0007` §8.5 records,
#: which every earlier separator tally in this portfolio got wrong.
_NUMBER = re.compile(r"\d[\d,.\u202f\u00a0\u2009]*\d|\d")


def _figures(text: str) -> set[str]:
    """Every number, reduced to its digits and decimal point."""
    return {token.translate(_SEPARATORS)
            for token in re.findall(_NUMBER, text)}


def test_every_figure_the_page_prints_is_one_a_committed_artifact_prints():
    """`ADR-0012`, and `0007` §5.0. The page quotes; it never retypes.

    Before S4 this page printed `728k rows/s` where `artifact_cost.md` prints `727,554` —
    a rounded number, which is a new number no reader can check. §5.0 sentence 2 is what
    makes that a violation rather than a style, and this is the only carrier that can see it:
    the index checker reads the page and the stylesheet and has no access to `reports/`.
    """
    # **What this cannot catch, measured rather than assumed.** Two of the four artifacts are
    # ADRs — prose, full of small integers — so a bare two-digit figure on the page is very
    # likely to be a whole token somewhere in them for an unrelated reason. Reintroducing
    # `23 %` in place of the cell's `0.23` passes here, because `ADR-0001` writes `n=23` about
    # a sample size. The guard is strong for a decimal or a figure of three digits or more,
    # and weak for a bare two-digit integer; versioning `results/probe/` would let the first
    # ADR come off the set and tighten it. Stated because a guard whose limit is not written
    # down is read as covering everything.
    unsourced = sorted(_figures(_rendered_text()) - _figures(_artifact_text()))
    assert not unsourced, (
        f"the page prints {unsourced}, which no committed artifact prints. Either the figure "
        "is a quotation and the artifact should be regenerated to produce it, or it is a new "
        "number and it does not belong on a page whose whole claim is that its figures are "
        "checkable."
    )


def test_the_exemptions_are_shapes_that_still_match_something():
    """A dead exemption is worse than none: it sits there widening the rule while covering
    nothing, and nobody notices because the suite stays green either way."""
    for pattern, why in _NOT_A_RESULT:
        assert re.search(pattern, PAGE, flags=re.DOTALL), (
            f"the exemption for {why} matches nothing on this page, so it can only widen "
            f"what the check above accepts: {pattern!r}"
        )


def test_each_headline_tile_quotes_the_cell_it_summarises():
    """`0007` §5 clause 2, whose binding the index checker cannot carry — it grants §5.1's
    fallback to any page with no tiles and cannot see whether an artifact could source one.

    Asserted per tile against the cell, not in aggregate: four tiles all quoting the same
    number would satisfy a set comparison and say nothing.
    """
    cost = (ROOT / "results" / "eval" / "report.md").read_text(encoding="utf-8")
    tiles = re.findall(r'<li class="kpi"><b>(.*?)</b><span>(.*?)</span>', PAGE, re.DOTALL)
    assert len(tiles) == 4, f"clause 2 asks for the tiles a reader scans first; found {len(tiles)}"
    for value, caption in tiles:
        digits = _figures(value)
        assert digits, f"the tile {caption!r} carries no figure"
        assert digits <= _figures(cost), (
            f"the tile {value!r} ({caption!r}) is not a cell of results/eval/report.md"
        )


def test_the_separator_and_the_code_ground_are_painted_apart():
    """The S3 defect, pinned in the repository it was loaded in.

    `#eef1f6` served two roles here — the table separator and `code`'s background — and a
    migration done by *value* maps both onto one token, leaves every name declared and
    resolvable, and ships a page both carriers report clean. The index checker's
    `1 usage roles` catches the separator half; **nothing catches the `code` half**, because
    a ground role in a ground property conforms whichever ground it names.

    Proved by the mutation it names: setting `code`'s background to `var(--border)` turns
    this red and leaves the checker reporting `clear`.
    """
    style = re.search(r"<style>(.*?)</style>", PAGE, re.DOTALL).group(1)
    separator = re.search(r"th,\s*td\s*\{[^}]*border-bottom:[^;]*var\(--([\w-]+)\)", style)
    ground = re.search(r"\bcode\s*\{[^}]*background:\s*var\(--([\w-]+)\)", style)
    assert separator, "no table separator painted with a token"
    assert ground, "no code background painted with a token"
    assert separator.group(1) == "border", (
        f"the table separator paints --{separator.group(1)}; six sibling pages write "
        "--border, and this page's own literal served that role"
    )
    assert ground.group(1) == "surface", (
        f"`code` paints --{ground.group(1)}; it is a ground, and --border is the edge"
    )
