"""The published page — and the rules the index checker structurally cannot carry.

`ADR-0004` (in the private index) puts one checker over all twelve published surfaces and
assertions in the repositories that have a page test. This repository had none, and S4 needs
one for a reason that is not convenience: **the checker reads a page's HTML and its CSS, and
cannot see this repository's artifacts.** So the two rules S4 is actually about are invisible
to it —

* *every figure the page prints is a figure a committed artifact prints* — it has nothing to
  compare against;
* *clause 2 binds where an artifact can source the tile* — its `clause_2_tiles` returns
  `n/a, §5.1 fallback applies` for any page with no tiles, before and after, because it
  cannot tell "exempt" from "nobody built tiles".

Everything else on this page — the ten tokens, the dark override, the wrapper, the eyebrow,
the card metadata, the system font stack, the separator — the checker does carry, and is not
restated here. Duplicating it in twelve places is the option `ADR-0004` rejected.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = (ROOT / "docs" / "index.html").read_text(encoding="utf-8")

#: The evaluation report, generated by `src/pl_jobs_lora/eval/report.py` and covered by
#: `tests/test_eval_report.py`. `.gitignore` keeps `results/eval/predictions/` out and says in
#: the same breath that *"only the numbers-only report.{json,md} is versioned"*.
REPORT = Path("results/eval/report.md")

#: What this page is allowed to quote.
ARTIFACTS = (
    REPORT,
    Path("results/eval/report.json"),
    # Two ADRs, named as sources rather than left as an exception. `results/probe/` is
    # gitignored, so the base-model probe's figures exist only in the ADR that recorded them,
    # and the corpus counts likewise. `ADR-0012` admits a committed non-generated source when
    # the page's artifact set names it - and naming it is what makes the alternative visible:
    # version `results/probe/` and the first of these two comes off this list.
    Path("docs/decisions/0001-base-model-selection.md"),
    Path("docs/decisions/0002-dataset-and-labeling.md"),
)

#: `0007` §5.0: a quotation is a digit sequence. The group separator is the page's typography —
#: clause 8 makes the page write `U+202F` where the artifact writes a comma — so both sides are
#: reduced to digits before comparing, and neither side's separator is part of the claim.
_SEP_CHARS = "\u202f\u00a0\u2009 "
_SEPARATORS = str.maketrans(dict.fromkeys("," + _SEP_CHARS, ""))

#: The figures inside the struck span, pinned. The exemption below removes a bounded span of
#: text, and pinning what it currently removes is what stops the span being widened later to
#: shelter a figure that is not withdrawn at all.
STRUCK = {"0.75", "0.87", "0.74", "4.9"}

#: Numbers a reader sees that are not results, cut out of the rendered text before tokenising
#: rather than excused afterwards. Each is a *shape* with a reason, never a value: a list of
#: allowed values goes stale in silence, which is what `0007` §5.0 sentence 2 is about.
_NOT_A_RESULT = (
    (r"\b(?:19|20)\d{2}-\d{2}-\d{2}\b", "a date is a fact about a run, not a cell of one"),
    # A model's name is an identifier. `Qwen2.5-1.5B` reads as the figures 2.5 and 1.5,
    # and `claude-haiku-4-5` as 4 and 5 - none of them a measurement of anything.
    (r"\b(?:Qwen|Bielik|Llama|Mistral)[\w.-]*", "a model name carries version digits"),
    (r"\bclaude-[\w-]+", "the API model's name"),
    # A figure the page has withdrawn, marked `<s class="withdrawn">` so a reader sees it is
    # not a claim. No artifact prints a number that was wrong, and forbidding it would forbid
    # the correction - the one section on this page whose whole subject is a figure that should
    # not have been published. **Bounded**: `.*?` under DOTALL exempted everything between the
    # tags, so appending ` / 9.99` inside the span was a free pass; the span holds no markup, so
    # `[^<]` is the honest limit, and `STRUCK` pins what it actually removes.
    (r'<s class="withdrawn">[^<]{0,240}</s>', "a figure the page has struck"),
)

#: The `content` of the three clause-5 properties that are **prose a reader reads** — a search
#: snippet and a social card. They carry figures, so the provenance rule reaches them; stripping
#: tags alone drops them along with the tag, which is what left `og:description`'s `0.01` and
#: `0.28` unguarded and free to go stale behind every edit of the body.
#:
#: `og:url`, `og:type` and `twitter:card` are deliberately **not** here. They are machine values,
#: and reading them as claims makes the account handle's `223` a figure the page has to source.
_META_CONTENT = re.compile(
    r'<meta\s+(?:name|property)="(?:description|og:title|og:description)"\s+content="([^"]*)"',
    re.IGNORECASE)


def _artifact_text() -> str:
    return "\n".join((ROOT / name).read_text(encoding="utf-8") for name in ARTIFACTS)


def _rendered_text(tally: dict[str, int] | None = None) -> str:
    """What a reader sees — the body, plus the published metadata a reader meets elsewhere.

    Comparing the **raw HTML** was the first attempt and it is hopeless — a URL's `223`, a
    hex literal's digits and an entity's `160` all read as claims, and the exemption list
    needed to silence them would be wider than the rule. `apply-scout`'s equivalent test
    reads rendered text for the same reason, and it is the reason.

    `tally`, when given, records how often each exemption fires **at the point it is applied**.
    That is the only place the question can be asked: by the time this function returns every
    exempted shape has been removed, so a pattern searched against the result always reads dead
    and a pattern searched against the raw page always reads alive.
    """
    def strip(text: str, flags: int = 0) -> str:
        for pattern, _why in _NOT_A_RESULT:
            text, fired = re.subn(pattern, " ", text, flags=flags)
            if tally is not None:
                tally[pattern] = tally.get(pattern, 0) + fired
        return text

    text = re.sub(r"<(style|script)\b.*?</\1>", " ", PAGE, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    meta = " ".join(_META_CONTENT.findall(text))
    # Twice on purpose: a shape written in markup — the struck span — has to go before the tags
    # do, and a shape written in prose only exists after they are gone.
    text = strip(text, re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text) + " " + meta
    text = re.sub(r"&#\d+;|&\w+;", " ", text)
    return strip(text)


#: A whole figure. **The plain space is not in the class**, though it is in
#: `_SEP_CHARS`: clause 8 makes a grouped figure use `U+202F`, and admitting the
#: ordinary space here welds two adjacent table cells into one token — `0.05 0.04`
#: reads as `0.050.04` and matches nothing. That is the welding `0007` §8.5 records,
#: which every earlier separator tally in this portfolio got wrong.
_NUMBER = re.compile(r"\d[\d,.\u202f\u00a0\u2009]*\d|\d")


def _canonical(digits: str) -> str:
    """`0007` §5.0 names the separator, the minus sign **and the presence or absence of a
    trailing zero** as the page's typography, so `67.90` and `67.9` are one quotation.

    Only after a decimal point: `100` is not `1`. This was a real divergence rather than a
    nicety — the test compared digit strings, so it was stricter than the sentence it cites,
    and it reported a legal typographic form as an unsourced figure.
    """
    if "." in digits:
        digits = digits.rstrip("0").rstrip(".")
    return digits or "0"


def _figures(text: str) -> set[str]:
    """Every number, reduced to its digits and decimal point."""
    return {_canonical(token.translate(_SEPARATORS)) for token in re.findall(_NUMBER, text)}


def _section(report: str, heading: str) -> str:
    """One heading's own text, up to the next heading of any level."""
    lines = report.splitlines()
    for start, line in enumerate(lines):
        if line.lstrip("#").strip() == heading and line.startswith("#"):
            for end in range(start + 1, len(lines)):
                if lines[end].startswith("#"):
                    return "\n".join(lines[start:end])
            return "\n".join(lines[start:])
    raise AssertionError(f"no section {heading!r} in the report")


def _cell(report: str, heading: str, row: str, column: str) -> str:
    """One cell of the report's table, addressed by the three things a reader would name."""
    lines = [ln for ln in _section(report, heading).splitlines() if ln.strip().startswith("|")]
    header = [c.strip() for c in lines[0].strip("|").split("|")]
    assert column in header, f"no column {column!r} under {heading!r}: {header}"
    index = header.index(column)
    for line in lines[2:]:
        cells = [c.strip() for c in line.strip("|").split("|")]
        if cells[0] == row:
            return cells[index]
    raise AssertionError(f"no row {row!r} under {heading!r}")


_MAIN = "Evaluation report (gold n=142)"

#: What each headline tile claims to be, in the order the page prints them: the word its caption
#: has to carry, and where in the report its figure comes from. Three are table cells addressed
#: by heading, row and column; the fourth is the report's own title line, which is where the
#: gold count is stated and is not a cell of anything.
#:
#: Naming the source is what makes clause 2 checkable. A set comparison against the whole file
#: cannot express it — four tiles printing one number satisfy it, and so does a tile printing
#: its neighbour's.
TILE_SOURCES = (
    ("tech_expected", ("cell", "Data ceiling (model-free)", "tech_expected", "ceiling on recall")),
    ("claude-haiku-4-5", ("cell", _MAIN, "claude-haiku-4-5__few", "field F1")),
    ("bielik-1.5b-gguf", ("cell", _MAIN, "bielik-1.5b-gguf__zero", "JSON valid")),
    ("gold", ("line", r"^#\s*Evaluation report \(gold n=\d+\)\s*$")),
)


def test_every_figure_the_page_prints_is_one_a_committed_artifact_prints():
    """`ADR-0012`, and `0007` §5.0. The page quotes; it never retypes.

    Before S4 this page printed `2.3`, `21.4` and `67.9` where `results/eval/report.md` prints
    `2.25`, `21.43` and `67.90` — rounded numbers, which are new numbers no reader can check.
    §5.0 sentence 2 is what makes that a violation rather than a style, and this is the only
    carrier that can see it: the index checker reads the page and the stylesheet and has no
    access to `results/`.
    """
    # **What this cannot catch, measured rather than assumed.** Two of the four artifacts are
    # ADRs — prose, full of small integers — so the set this page is checked against is very
    # wide: 262 figures admitted, 39 of them bare one- or two-digit integers. Swept by
    # substituting one digit at a time, **56 of the 59 figures this page prints have at least
    # one corruption this test accepts**, including `0.28` → `0.27`, which retypes the ceiling
    # as the value actually reached. Reintroducing `23 %` in place of the cell's `0.23` passes
    # outright, because `ADR-0001` writes `n=23` about a sample size.
    #
    # So this test is a floor, not the guard: it catches a figure that appears *nowhere*, and
    # the tile test below is what binds a figure to the cell it claims to be. Versioning
    # `results/probe/` would take the first ADR off the set and narrow this considerably.
    # Stated with its definition, because a census whose corruption family is unstated is a
    # number nobody can reproduce, and a guard whose limit is unwritten is read as total.
    unsourced = sorted(_figures(_rendered_text()) - _figures(_artifact_text()))
    assert not unsourced, (
        f"the page prints {unsourced}, which no committed artifact prints. Either the figure "
        "is a quotation and the artifact should be regenerated to produce it, or it is a new "
        "number and it does not belong on a page whose whole claim is that its figures are "
        "checkable."
    )


def test_the_exemptions_are_shapes_that_still_fire_where_they_are_applied():
    """A dead exemption is worse than none: it sits there widening the rule while covering
    nothing, and nobody notices because the suite stays green either way.

    Asked of the **pipeline**, not of the page. The first version searched the raw HTML, which
    answers a different question and always answers yes: every shape here is still in the markup
    long after the pass that consumed it, and a shape that fires on nothing a reader sees reads
    alive there all the same.
    """
    tally: dict[str, int] = {}
    _rendered_text(tally)
    for pattern, why in _NOT_A_RESULT:
        assert tally.get(pattern), (
            f"the exemption for {why} fires on nothing a reader sees, so it can only widen "
            f"what the check above accepts: {pattern!r}"
        )


def test_the_struck_span_holds_the_figures_it_is_allowed_to_hide():
    """The one exemption whose subject *is* a figure, so its content is pinned rather than
    described. Widening the span to shelter a live figure now has to be written into this set."""
    span = re.search(r'<s class="withdrawn">([^<]{0,240})</s>', PAGE)
    assert span, "no struck span on the page, so the exemption above covers nothing"
    assert _figures(span.group(1)) == STRUCK, (
        f"the struck span hides {sorted(_figures(span.group(1)))}; this test allows "
        f"{sorted(STRUCK)}. A figure the page has withdrawn is exempt from provenance; "
        "anything else is not."
    )


def test_each_headline_tile_quotes_the_cell_it_summarises():
    """`0007` §5 clause 2, whose binding the index checker cannot carry — it grants §5.1's
    fallback to any page with no tiles and cannot see whether an artifact could source one.

    Bound to the source, by heading, row and column. Comparing each tile against every figure in
    the file is the aggregate comparison this docstring used to claim it avoided while
    performing it: four tiles all printing `0.51` passed, and so did a tile printing the ceiling
    `0.28` as the achieved value `0.27`. The caption is checked for the word that names the
    source, so a tile cannot describe one variant and quote another.
    """
    report = (ROOT / REPORT).read_text(encoding="utf-8")
    tiles = re.findall(r'<li class="kpi"><b>(.*?)</b><span>(.*?)</span>', PAGE, re.DOTALL)
    assert len(tiles) == len(TILE_SOURCES), (
        f"clause 2 asks for the tiles a reader scans first; found {len(tiles)}"
    )
    for (value, caption), (label, source) in zip(tiles, TILE_SOURCES, strict=True):
        assert label in caption, (
            f"the tile {value!r} is sourced from {label!r} and its caption {caption!r} does not "
            "name it, so a reader cannot tell which measurement it is"
        )
        if source[0] == "cell":
            text = _cell(report, *source[1:])
        else:
            line = re.search(source[1], report, re.MULTILINE)
            assert line, f"the report has no line matching {source[1]!r}"
            text = line.group(0)
        assert _figures(value) == _figures(text), (
            f"the tile {value!r} ({caption!r}) is not what the report prints there, "
            f"which reads {text!r}"
        )


def test_every_ground_is_painted_with_the_role_that_names_it():
    """The S3 defect, pinned in the repository it was loaded in — and pinned at every site.

    `#eef1f6` served two roles here — the table separator and `code`'s background — and a
    migration done by *value* maps both onto one token, leaves every name declared and
    resolvable, and ships a page both carriers report clean. The index checker's
    `1 usage roles` catches the separator half; **nothing catches a ground half**, because a
    ground role in a ground property conforms whichever ground it names.

    Asserted over the **whole** ground map and over **every** declaration of each selector.
    Pinning `code` alone left `tr.ours td { background: var(--bg) }` clean on both carriers, and
    pinning the first match left a later `@media (prefers-color-scheme: dark) { code { … } }`
    free to repaint it: CSS resolves by the last declaration and `re.search` returns the first.
    """
    style = re.search(r"<style>(.*?)</style>", PAGE, re.DOTALL)
    assert style, "the page has no inline stylesheet, so nothing below can be read"
    css = style.group(1)

    separator = re.search(r"th,\s*td\s*\{[^}]*border-bottom:[^;]*var\(--([\w-]+)\)", css)
    assert separator, "no table separator painted with a token"
    assert separator.group(1) == "border", (
        f"the table separator paints --{separator.group(1)}; six sibling pages write "
        "--border, and this page's own literal served that role"
    )

    for selector, role in (("body", "bg"), (r"tr\.ours td", "surface"), ("code", "surface")):
        painted = re.findall(
            r"(?:^|[;{}])\s*" + selector + r"\s*\{[^}]*background:\s*var\(--([\w-]+)\)",
            css, re.MULTILINE)
        assert painted, f"no `{selector}` background painted with a token"
        assert set(painted) == {role}, (
            f"`{selector}` paints {sorted(set(painted))} across {len(painted)} declaration(s); "
            f"it is this page's {role} and every scheme has to agree on that"
        )


def test_a_trailing_zero_is_typography_and_not_a_different_figure():
    """`0007` §5.0's own sentence, made executable. The rule and its implementation disagreed:
    the spec calls a trailing zero typography and this function compared digit strings, so
    `67.90` quoted as `67.9` read as a figure no artifact prints."""
    assert _figures("67.90") == _figures("67.9")
    assert _figures("4.0 %") == _figures("4 %")
    assert _figures("0.00") == _figures("0")
    assert _figures("100") != _figures("1"), "only a decimal tail is typography"
